[client]
httpRequestTimeout = 1000000
[token]
apimVersion = ""
publisherEndpoint = ""
adminEndpoint = ""
registrationEndpoint = ""
tokenEndpoint = ""
username = ""
clientId = ""
clientSecret = ""
trustStoreLocation = ""
trustStorePassword = ""

[corsConfiguration]
corsConfigurationEnabled=true
accessControlAllowOrigins=["*"]
accessControlAllowMethods=["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
accessControlAllowHeaders=["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
accessControlAllowCredentials=false

[codeGen]
apiFaultResponses = false
globalFaultResponses = false
